config/routes.rb
Depot::Application.routes.draw do
  root :to => 'store#index', :as => 'store'
  
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>X-axis Bookshop</title>
<!-- START:stylesheet -->
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %><!-- <label id="code.slt"/> -->
<!-- END:stylesheet -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> -->
</head>
<body id="store">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "X-axis Bookshop" %><!-- <label id="code.depot.e.title"/> -->
  </div>
  <div id="columns">
    <div id="side">
	  <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>
	  <div id="cart">
	  
		
	  </div>
      <a href="http://www....">Home</a><br />
	  <a href="http://www..../about">About</a><br />
      <a href="http://www..../review">Book Reviews</a><br />
	  <a href="http://www..../faq">Help</a><br />
      <a href="http://www..../contact">Contact</a><br />
	  
	  <% if session[:user_id] %>
        <br />
        <%= link_to 'Orders', orders_path %><br />
        <%= link_to 'Products', products_path %><br />
        <%= link_to 'Users', users_path %><br />
        <br />
        <%= button_to 'Logout', logout_path, :method => :delete %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
    </div>
  </div>
</body>
</html>